version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/appcinema/
    ports:
      - "8000:8000"
    depends_on:
      - migrations
  migrations:
    build: .
    command: bash -c "python3 manage.py migrate --noinput && python3 manage.py loaddata fixture.json"
    volumes:
      - .:/appcinema/
