apiVersion: v1
kind: Service
metadata:
  name: appcinemaweb
  labels:
    apps: appcinemaweb
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: web-port
    protocol: TCP
  selector:
    app: appcinemaweb